---
config:
  adaptor_port: 10010
  adaptor: adaptor
  simulator: taskmanager
  scheduler: actormanager
  adaptor_address: greencharge.local
  workingdir: /home/salvatore/users/eurecat/bin
  userjid: eurecat@greencharge.local
  simulation: salvatore
  simulation_dir: /home/salvatore/users/eurecat/Simulations
  protocol: "1.0"
  date: 12/12/15
  xmpp_password: greencharge
  webdir: /home/salvatore/public_html
...
