---
config:
  adaptor_port: 10010
  adaptor: adaptor
  simulator: taskmanager
  scheduler: actormanager
  adaptor_address: greencharge.local
  workingdir: /home/users/demo/bin
  userjid: demo@greencharge.local
  simulation: provaSim
  simulation_dir: /home/users/demo/Simulations
  protocol: "1.0"
  date: 12/12/15
  xmpp_password: greencharge
  webdir: /var/www/html/Simulations
...
